### ISSUE TITLE
Incorrect file names of BrainSlices template command bash files

### ISSUE THREAD

**Issue by martcous** [ntustison/TemplateBuildingExample#2]
Hi Nick!

I think the two following template command bash files have incorrect names.
*BrainSlices/templateCommandMultivariateBSplineSyN.sh* seems to perform TimeVaryingVelocityField transformation, while *BrainSlices/templateCommandTimeVarying.sh*  seems to perform BSplineSyN transformation.

As a side note, I think it would be helpful for new users to briefly explain the differences between the four template command bash files of BrainSlices in the readme.

Merci,
Martin

**Comment by ntustison** [comment]
Hi Martin,

Thanks for this.  I think it's fixed now.  Also, I added to the documentation.

Thanks,
Nick
