### ISSUE TITLE
Wrong parameter k in the script

### ISSUE THREAD

**Issue by John1231983** [ntustison/TemplateBuildingExample#3]
Hello, you only used T1 to construct a template, so I think k should be 1 instead of 2

https://github.com/ntustison/TemplateBuildingExample/blob/bd274dd1a0e07759b732be9842b7922e24a3f23b/BrainSlices/templateCommandMultivariateBSplineSyN.sh#L11

Am I correct?

**Comment by ntustison** [comment]
No, it's correct.  Both T1 and Laplacian images are used.
