### ISSUE TITLE
Problem using templateCommandSyN.sh to create population template for ADNI 1

### ISSUE THREAD

**Issue by Xin-Ma-1** [ntustison/TemplateBuildingExample#4]
Hi Nick! I tried to use the same parameters in `BrainSlices/templateCommandSyN.sh` (only changed dimension to 3) to process a group of normal controls from ADNI 1 study to create a population template. But the image I obtained looks very distorted and blurred. From the paper "Tustison, Nicholas J., et al. "The ANTs longitudinal cortical thickness pipeline." BioRxiv (2017): 170209." I know you have made template files for similar ADNI 1 subjects. Would you mind sharing the parameters you have used for this job or even sharing the template files? Thank you!

**Comment by ntustison** [comment]
Hi @Xin-Ma-1 --- sure, [here's a link to the template](https://drive.google.com/drive/folders/0B4SvObeEfaRyaUlYZ1VueFlCSkU?usp=sharing).  And note that the updated publication is [here](https://www.ncbi.nlm.nih.gov/pubmed/31356207).

**Comment by Xin-Ma-1** [comment]
@ntustison This is really helpful! Thank you!
